### ISSUE TITLE
Confusing UI

### ISSUE THREAD

**Issue by fasidOnGit** [chennai-js/covid-info#10]
Currently, the colors on the numbers are confusing.

![image](https://user-images.githubusercontent.com/27940795/115956157-df5acc80-a518-11eb-9520-cde4ec6b0ce6.png)

**Comment by udhaya0000** [comment]
I think we need to improve the UX

**Comment by saravanan10393** [comment]
Yes guys, as of now we have mimiced the UX of covidpune site. if you guys find better ux, we defintely improve it.

**Comment by fasidOnGit** [comment]
@saravanan10393 @udhaya0000 We need a UX person. I am already talking with a friend of mine. if there are other people available may be they could join hands here.
