### ISSUE TITLE
Prepare Dataset Bed and Medicine availability in each hospital.

### ISSUE THREAD

**Issue by saravanan10393** [chennai-js/covid-info#2]

**Comment by saravanan10393** [comment]
@zerothabhishek kindly share the google sheet link here, so that people develop the home page

**Comment by zerothabhishek** [comment]
Beds data can be fetched from here:

https://github.com/stopcoronatn/stopcoronatn.github.io/blob/main/data/beds.csv

Additional data (address, phone number, map link etc) is present in this sheet:

https://docs.google.com/spreadsheets/d/1t75_AfDuf46_aK6RwqUwZGpZV4dv9y0SWaI9pnJRAco/edit#gid=2141296668

**Comment by zerothabhishek** [comment]
Here's a mirror of the spreadsheet data as json:

https://covidchennai.h65.in/hospitals.data.json

**Comment by saravanan10393** [comment]
Ok @zerothabhishek will do the home page today and push

**Comment by saravanan10393** [comment]
@zerothabhishek need to enable CORS support for this  [https://covidchennai.h65.in/hospitals.data.json](https://covidchennai.h65.in/hospitals.data.json) json

**Comment by zerothabhishek** [comment]
Ok @saravanan10393 

I'll need to cleanup the data a little bit too. Will do that also today

**Comment by saravanan10393** [comment]
@zerothabhishek I have pushed basic home page setup. Going to work on the deployment part
