### ISSUE TITLE
Feature: Direct button to List ICU beds

### ISSUE THREAD

**Issue by zerothabhishek** [chennai-js/covid-info#27]
We need a button/link on top, which can filter the data, and show all the hospitals with available ICU beds; in the selected city 

Rationale: Most people who come on the site are in need of ICU beds only. Lets make the job easier for them.

**Comment by zerothabhishek** [comment]
@vctc want to take a stab at this ?

**Comment by vctc92** [comment]
> 
> 
> @vctc want to take a stab at this ?

I will do this.
