### ISSUE TITLE
Mobile view options revamp

### ISSUE THREAD

**Issue by fasidOnGit** [chennai-js/covid-info#29]
Currently, the mobile view has very less space for the lists. I can only see a couple of list items. this is not ideal. as the filters and other options grow, they are taking over the majority of the screen. We could solve this by allowing filtering in a popup modal while in mobile.
![image](https://user-images.githubusercontent.com/27940795/116779487-06267f00-aa94-11eb-9ba7-9a2744fa8e78.png)

**Comment by vctc92** [comment]
![image](https://user-images.githubusercontent.com/4219835/116818660-32bcc280-ab8a-11eb-854e-b07fb65445e5.png)
We can try to reduce the size and design of upper half in mobile view
