### ISSUE TITLE
Finalising deployment platform

### ISSUE THREAD

**Issue by saravanan10393** [chennai-js/covid-info#6]

**Comment by saravanan10393** [comment]
Need to decide which deployment platform we are going to host this app. Need to compare which platform provides high bandwidth for free.

**Comment by jenishngl** [comment]
GitHub actions with firebase hosting?

**Comment by Rafi993** [comment]
Netlify or vercel might be quicker to setup and they do provide free tier  or even Github pages could be used :)

**Comment by zerothabhishek** [comment]
I'm also leaning on Netlify or Vercel. Because we have experience with them, and also they have *functions* if need in future.

**Comment by zerothabhishek** [comment]
Btw, I've registered the covidchennai.org domain. Once we have something deployed, I'll point it

**Comment by fasidOnGit** [comment]
I vote for Netlify. since they have site previews for PRs.
